// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SISC.Data;

#nullable disable

namespace SISC.Data.Migrations.Simulacoes
{
    [DbContext(typeof(SimulacoesDbContext))]
    partial class SimulacoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("SISC.Models.Simulacao.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultadoSimulacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorAmortizacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorJuros")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPrestacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoSimulacaoId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("SISC.Models.Simulacao.ResultadoSimulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("SimulacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoId");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("SISC.Models.Simulacao.Simulacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prazo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxaJuros")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorDesejado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("SISC.Models.Simulacao.Parcela", b =>
                {
                    b.HasOne("SISC.Models.Simulacao.ResultadoSimulacao", "Resultado")
                        .WithMany("Parcelas")
                        .HasForeignKey("ResultadoSimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("SISC.Models.Simulacao.ResultadoSimulacao", b =>
                {
                    b.HasOne("SISC.Models.Simulacao.Simulacao", "Simulacao")
                        .WithMany("Resultados")
                        .HasForeignKey("SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("SISC.Models.Simulacao.ResultadoSimulacao", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("SISC.Models.Simulacao.Simulacao", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
