// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SISC.Data;

#nullable disable

namespace SISC.Data.Migrations.Produtos
{
    [DbContext(typeof(ProdutosDbContext))]
    [Migration("20250822011552_InitialCreateProdutos")]
    partial class InitialCreateProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SISC.Models.Produto.Produto", b =>
                {
                    b.Property<int>("CoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CO_PRODUTO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoProduto"));

                    b.Property<string>("NoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NO_PRODUTO");

                    b.Property<short>("NuMaximoMeses")
                        .HasColumnType("smallint")
                        .HasColumnName("NU_MAXIMO_MESES");

                    b.Property<short>("NuMinimoMeses")
                        .HasColumnType("smallint")
                        .HasColumnName("NU_MINIMO_MESES");

                    b.Property<decimal>("PcTaxaJuros")
                        .HasPrecision(16, 9)
                        .HasColumnType("decimal(16,9)")
                        .HasColumnName("PC_TAXA_JUROS");

                    b.Property<decimal>("VrMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VR_MAXIMO");

                    b.Property<decimal>("VrMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VR_MINIMO");

                    b.HasKey("CoProduto");

                    b.ToTable("PRODUTO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
